### ISSUE TITLE
哭了都

### ISSUE THREAD

**Issue by ZJ-Zhang-0906** [hakuei0115/File-Copy-Tool#1]
My English is bad ,could you please write Readme.md of Chinese version for me?

**Comment by hakuei0115** [comment]
OK, I will check my schedule.

**Comment by hakuei0115** [comment]
? I thourght it already have README_CN.

**Comment by ZJ-Zhang-0906** [comment]
Oh I see my bad

**Comment by ZJ-Zhang-0906** [comment]
👍

**Comment by hakuei0115** [comment]
高強度刷github 連我關閉issue都能發覺

**Comment by ZJ-Zhang-0906** [comment]
笑死

Borui.Lin ***@***.***>於 2024年4月24日 週三，16:15寫道：
